// Generates src/styles/palettes.generated.css from src/styles/palettes.ts.
// Run via `pnpm run palettes` (also part of `pnpm run build:all`).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { palettes, type PaletteTokens } from '../src/styles/palettes.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '../src/styles/palettes.generated.css');

function block(t: PaletteTokens): string {
  return [
    `  --bg: ${t.bg};`,
    `  --surface: ${t.surface};`,
    `  --raised: ${t.raised};`,
    `  --text: ${t.text};`,
    `  --text-muted: ${t.textMuted};`,
    `  --text-subtle: ${t.textSubtle};`,
    `  --border: ${t.border};`,
    `  --border-strong: ${t.borderStrong};`,
    `  --accent: ${t.accent};`,
    `  --accent-text: ${t.accentText};`,
    `  --on-accent: ${t.onAccent};`,
    `  --danger: ${t.danger};`,
    `  --danger-text: ${t.dangerText};`,
  ].join('\n');
}

const parts: string[] = [
  '/* Generated by scripts/build-palettes.ts — do not edit by hand. */',
];

for (const [name, palette] of Object.entries(palettes)) {
  parts.push(`:root[data-palette='${name}'] {\n${block(palette.light)}\n}`);
  parts.push(
    `@media (prefers-color-scheme: dark) {\n  :root[data-palette='${name}']:not([data-theme='light']) {\n${block(
      palette.dark,
    )
      .split('\n')
      .map((l) => '  ' + l)
      .join('\n')}\n  }\n}`,
  );
  parts.push(`:root[data-palette='${name}'][data-theme='dark'] {\n${block(palette.dark)}\n}`);
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, parts.join('\n\n') + '\n', 'utf-8');
console.log(`Generated ${outPath}`);
